### ISSUE TITLE
[BUG] CodeCov CI fails when running from a fork

### ISSUE THREAD

**Issue by AndreasLrx** [AndreasLrx/ecstasy#169]
### Current Behavior

CodeCov CI fails  when the repository is not the original one, because the codecov key does not have access to the forked repository. 
(See pr #168 for example)

### Expected Behavior

Either find a way to fix this, or just skip the codecov part when running CI from forks

**Comment by osvegn** [comment]
Take a look at this issue https://github.com/codecov/codecov-action/issues/29, it seems a lot of people already has trouble with it without any solution except using another tool
